### ISSUE TITLE
Card overflow when creating mini budget

### ISSUE THREAD

**Issue by abumunye** [abumunye/orderpin-bugs#10]
## Describe the bug
When creating a mini budget the date overflows off the card

## To Reproduce
1. Sign in
2. Click the + button on the bottom right
3. Click mini budget add
4. Observe the start date and end date overflowing off the card

## Expected behavior
The card should be responsive and not overflow 

## Screenshots
<img src="https://user-images.githubusercontent.com/40043711/159259756-0d349264-fe0e-4eef-ac48-e0865785abae.png" width="300">

## Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 9

**Comment by xmxdeus** [comment]
Bug Fixed
