### ISSUE TITLE
Searching for ads in the market place will make grey screen

### ISSUE THREAD

**Issue by abumunye** [abumunye/orderpin-bugs#14]
## Describe the bug
If you use the search bar on the marketplace and try search something then you get a grey screen

## To Reproduce
1. Sign in
2. Swipe left to right
3. Open marketplace
4. Try and type something in the search bar

## Expected behavior
Should be able to type in the search bar to filter out the list of ads

## Screenshots
<img src="https://user-images.githubusercontent.com/40043711/159265778-7f2eafaf-2ae8-423f-af24-d61cf141a04a.png" width="300">

## Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 9

**Comment by xmxdeus** [comment]
Bug fixed
