### ISSUE TITLE
Different food categories have the same food items

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#143]
## Describe the bug
When you press on the different food categories all of the options are all the same 

## To Reproduce
1. Go to 'Take away order'
2. Click on 'eat in'
3. Click on 'different menu option'

## Expected behavior
There are different meals for each section
## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177280993-cda41711-e2aa-4a0d-906c-9bfc93255b74.png)

![image](https://user-images.githubusercontent.com/102152014/177281060-2c044ecd-36a6-4cee-b2c6-f6e3876b5e2e.png)

## Smartphone (please complete the following information):
 - Device: [Android Tablet]

**Comment by abumunye** [comment]
This is not a bug. The menu is created from manager panel.
