### ISSUE TITLE
No information on Vegan or desert

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#144]
## To Reproduce
1. Go to 'Eat in'
2. Click on 'Take away orders'
3. Scroll down to 'Dessert or vegan'

## Expected behavior
There will be options for vegan and desert

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177281378-04831cf1-33c7-4f55-b9fb-66bdb499ce1f.png)
![image](https://user-images.githubusercontent.com/102152014/177281392-e3dde0bb-c089-452a-92c2-789a0dc15bc2.png)

## Smartphone (please complete the following information):
 - Device: [Android Tablet]

**Comment by abumunye** [comment]
This is not a bug. The menu is created from manager panel.
