### ISSUE TITLE
New Customer

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#145]
## Describe the bug
When an error message comes up the screen becomes disjointed, the buttons stops working and you have to reset the whole form

## To Reproduce
1. Go to 'new order'
2. Click on 'eat in'
3. Click on 'take away'
4. Click on: 'New customer'
5. See error

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177282703-5d80ed51-3e9c-4cb0-8cbe-c1ff403e3903.png)

## Smartphone (please complete the following information):
 - Device: [Assigned android tablet]

**Comment by abumunye** [comment]
fixed

**Comment by TamarindSpice** [comment]
completed 

![image](https://user-images.githubusercontent.com/102152014/182593277-ba2175b0-8cf1-45e1-8945-7c436d37ca46.png)
