### ISSUE TITLE
Repeat order button not working

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#147]
## To Reproduce
1. Go to 'new order'
2. Click on 'eat in'
3. Scroll down to 'Repeat order'

## Expected behavior
You are able to repeat the last order after having selected the customer

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177283892-c8301025-c9dd-4d42-a257-1402fb6d525f.png)

## Smartphone (please complete the following information):
 - Device: [Android]

**Comment by abumunye** [comment]
Feature not implemented yet so I removed it for now
