### ISSUE TITLE
Discount options without cap allows for errors

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#148]
## Describe the bug
There is not cap on the discount which allows for odd numbers to be placed

## To Reproduce
1. Go to 'New order'
2. Click on 'eat in'
3. Scroll down to 'Discount'

## Expected behavior
There should be a cap for this discount which will not allow for a mistake.

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177284490-3700480d-c001-4a29-85d4-4ffd2f89de17.png)

![image](https://user-images.githubusercontent.com/102152014/177284516-fe2c6ac2-ffe6-479f-a490-96a0f921215c.png)

## Smartphone (please complete the following information):
 - Device: [Android Tablet]

**Comment by TamarindSpice** [comment]
Issue still present
![image](https://user-images.githubusercontent.com/102152014/182582582-b08534c1-de69-4663-b248-2fb324281699.png)

**Comment by abumunye** [comment]
fixed
