### ISSUE TITLE
Big numbers come of screen

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#149]
## Describe the bug
If the number is too big it comes off the screen instead of the whole number being on on line

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177285325-35c9b22f-bb0a-415c-b18d-c3d28d8dbaaa.png)

## Smartphone (please complete the following information):
 - Device: [Android tablet]

**Comment by abumunye** [comment]
fixed

**Comment by TamarindSpice** [comment]
thanks

![image](https://user-images.githubusercontent.com/102152014/182580841-c4d111fe-bd2b-472a-8bbc-b333dc13c52d.png)
