### ISSUE TITLE
Details for card do not come up

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#152]
## Describe the bug
When you press on the card option it comes up as automatically being paid even though no information has been filled in

## Expected behavior
When pressing on the card option the details come up to fill in 

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177287990-eceddec9-1950-4a00-bf10-43ca9841269f.png)

## Smartphone (please complete the following information):
 - Device: [Android]

**Comment by abumunye** [comment]
fixed

**Comment by TamarindSpice** [comment]
thanks, closed
