### ISSUE TITLE
Table order not registering

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#153]
## Describe the bug
When a table order is placed it should appear on the main screen

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177288415-56b409eb-b1d7-4cee-bdb3-15c1dee87435.png)

should come up like these orders:
![image](https://user-images.githubusercontent.com/102152014/177288495-d84aa35f-f7a8-476b-ab67-fde250ddee21.png)

## Smartphone (please complete the following information):
 - Device: [Android tablet]

**Comment by abumunye** [comment]
Not a bug. If you want the table order to show click hold order
