### ISSUE TITLE
Bell all sounding when entering app

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#160]
## Describe the bug
The bell always goes off when I enter the app even when there is no new order extt.

## Expected behavior
Only sounds when there is a new order

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177508980-4af4a69e-f750-491c-b46d-b65f3017a367.png)

## Smartphone (please complete the following information):
 - Device: [Android Tablet]

**Comment by abumunye** [comment]
Fixed for ri8cart and ignite360. The sound was to notify that internet speed is low or printer is disconnected. Now there should be a text on the top of live order page to tell you.

**Comment by TamarindSpice** [comment]
thanks
