### ISSUE TITLE
Make Payment not working

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#162]
## Describe the bug
You are unable to submit a payment
Unclear: What is the reference number in relation to? 
Unclear: No card details asked for

## To Reproduce
1. Go to 'Make Payment'
2. Fill in details
3. See error

## Expected behavior
You can submit a payment

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/177509915-0e9ce2e0-c9c2-4e90-8f19-8f151bc2a534.png)

## Smartphone (please complete the following information):
 - Device: [Android Tablet]

**Comment by abumunye** [comment]
fixed
