### ISSUE TITLE
Hussain restaurant: front alert & ignite360 voucher error

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#197]
## Describe the bug
The words for the discount are spilling outside of the parameters of the box

## To Reproduce
1. Go to 'New order'
2. Click on 'Biriyani'
3. Scroll down to 'card discount'

## Expected behavior
The words are within the boundary of the box

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/179539049-ca54405e-06c6-4954-9ff8-76869593132a.png)

## Smartphone (please complete the following information):
 - Device: [Alba device given by Salim]
 - OS: [Android]

**Comment by abumunye** [comment]
Fixed
