### ISSUE TITLE
Dine in still not showing on order page

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#205]
## Describe the bug
The dine in orders are to registering on the order page

## Expected behavior
When I order on the dine in section it appears on the order page

## Screenshots
[<img src="insert url to image here" width="300">](https://www.dropbox.com/s/kdier1wd70i0nyn/WhatsApp%20Video%202022-07-28%20at%209.51.08%20AM.mp4?dl=0)

## Smartphone (please complete the following information):
 - Device: [Tablet Salim gave]
 - OS: [Android]

**Comment by TamarindSpice** [comment]
You can press on the image to see the video

**Comment by abumunye** [comment]
If you want dine in order to show you must click hold. If you finish your dine in order it wont show on live orders page because it means that the customer has already left.
