### ISSUE TITLE
Text is overspilling

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#206]
## Describe the bug
The text is spilling over the boundaries of the boxes

## To Reproduce
1. Go to 'New Order'
2. Click on 'deliver'
3. Scroll down to '.discount

## Expected behavior

the text is within the box

## Screenshots
![image](https://user-images.githubusercontent.com/102152014/182582883-b20d127a-95ef-4df6-a46c-2a5e05b50fab.png)

## Smartphone (please complete the following information):
 - Device: [Tablet given by salim]
 - OS: [Android]

**Comment by abumunye** [comment]
fixed
