### ISSUE TITLE
Monthly and weekly check showing resolve when resolved

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#214]
## Describe the bug
The check say that it is yet to be resolved and is in the red color however when i press on it the form changed as shows that it has been filled in

## To Reproduce
1. Go to 'food hygiene'
2. Click on 'records'
3. Scroll to the side to 'monthly/weekly'

## Expected behavior
A clear and concise description of what you expected to happen.4

![image](https://user-images.githubusercontent.com/102152014/183860236-8aed838e-e4bd-4b99-aa3b-39eff07e3a7e.png)

if the check has already been submitted then it should turn green and say resolved 
## Screenshots

![image](https://user-images.githubusercontent.com/102152014/183860122-04221a05-0fe4-40a5-a759-f3b3d8fd83a2.png)

![image](https://user-images.githubusercontent.com/102152014/183860153-277c9b50-624b-41f1-8232-2837d87612e5.png)

![image](https://user-images.githubusercontent.com/102152014/183860200-3b48a7ca-911b-4b25-a79c-91629b063092.png)

## Smartphone (please complete the following information):
 - Device: [Alba]
 - OS: [Android]

**Comment by abumunye** [comment]
looks like it's fixed
