### ISSUE TITLE
Order notes button not available for deliver and collection options

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#220]
## Describe the bug

Unlike for the Dine in section there is no order note button which is available for collection and for delivery although when viewing the receipt on ChefsBucket this option is expected and says 'order note: none' although the option was never given in the first place at the check out section 

## To Reproduce
1. Go to 'New Order'
2. Click on 'delivery/collection'
3. Scroll down to 'whole page'
4. See error 'no option availible'

## Expected behavior

Just like for dine in the is a button to add notes for collection and delivery

## Screenshots
If applicable, add screenshots to help explain your problem

the button is available on dine in

![image](https://user-images.githubusercontent.com/102152014/184109521-1a1ba2fe-2a48-4127-8b90-80e1320693a5.png)

Not available for delivery

![image](https://user-images.githubusercontent.com/102152014/184109573-cb3d6f50-dea3-49eb-9ce5-ec0abe9f944e.png)

not available for collection

![image](https://user-images.githubusercontent.com/102152014/184109631-ff582fb3-d5ef-4135-9eb0-f70420d2cbdb.png)

## Smartphone (please complete the following information):
 - Device: [Alba tablet ]
 - OS: [Android]

**Comment by abumunye** [comment]
This is not a bug
