### ISSUE TITLE
Code at the bottom of the picture -Expense tracker page

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#23]
On the expense tracker page using the guest account the code at the bottom of the image can be seen in comparison to the other page (income) where the writing at the bottom isn't code and it has no underscores.

## Expected behavior
On the income page there is only text not the code --> "Add a new..." instead of "Add_expences_....."

## Screenshots

![WhatsApp Image 2022-03-22 at 10 23 23](https://user-images.githubusercontent.com/102152014/159675067-967b9fe8-894b-4228-9d08-9d9c1ea93229.jpeg)

![WhatsApp Image 2022-03-22 at 10 08 10](https://user-images.githubusercontent.com/102152014/159675079-648d7c87-84ac-45fc-9ed1-49b4ba532090.jpeg)

## Smartphone (please complete the following information):
 - Device: [ Samsung]
 - OS: [Android]

**Comment by xmxdeus** [comment]
Bug Fixed
