### ISSUE TITLE
Post a request page

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#24]
## Describe the bug
At the top of the page there is lorep ipsum code still available
capital P for phone number

## To Reproduce
1. Go to 'Market place '
2. Click on 'plus button'
3. Scroll down to 'top of the page'

## Expected behavior
you will see te Lorep Ipsum text at the top and if you scroll down you will see a small p for phone number 

## Screenshots
<img src="insert url to image here" width="300">
![WhatsApp Image 2022-03-22 at 10 01 38](https://user-images.githubusercontent.com/102152014/159676395-8d6c354b-13e4-43b7-9a1b-dda0a4a63f1e.jpeg)
]

## Smartphone (please complete the following information):
 - Device: [Samsung]
 - OS: [android ]

**Comment by xmxdeus** [comment]
Bug Fixed
