### ISSUE TITLE
Displaced sign up box

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#250]
## Describe the bug
the section for entering information is displaced to the top left hand side in both portrait and landscape mode

## To Reproduce
1. Go to 'sign in page'
2. Click on 'sign up'

## Expected behavior
the sign up section is centered on the page.

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/186840893-2aa4a753-a6e3-43ce-aaa8-40ba721549d9.png)

![image](https://user-images.githubusercontent.com/102152014/186840927-60ff8124-229c-4652-9fe1-c638347c9a7d.png)

## Smartphone (Alba tablet):
 - OS: [Android]

**Comment by abumunye** [comment]
Fixed
