### ISSUE TITLE
You can not hide your password

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#251]
## Describe the bug

When pressing the eye button you cannot hide your password when placing it in

## To Reproduce
1. Go to 'home page sign up'
2. Click on 'eye icon'
3. write '.password

## Expected behavior
When pressing the eye button the password should be concealed as dots or stars

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/186841529-530d2e1e-0f3c-472a-aa84-96340ccab1a8.png)

## Desktop (Alba tablet from Manager Salim):
 - OS: [android]
 - Browser [Chrome]

**Comment by abumunye** [comment]
Fixed
