### ISSUE TITLE
currency to one decimal place

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#254]
## Describe the bug
The currency is to one decimal place and not two eg. £2.2 or £40.5 instead of £2.20 and £40.50

## To Reproduce
1. Go to 'Check out section of restaurant after pressing some items'
2. . See error

## Expected behavior
the currency is to two decimal places

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/186843803-1ae22aa5-b68b-4b17-a684-14116436af2d.png)

![image](https://user-images.githubusercontent.com/102152014/186843814-593f6025-deb0-4dae-b399-018f9d206f60.png)

## Desktop (Alba Tablet):
 - OS: [Android]
 - Browser [Chrome]

**Comment by abumunye** [comment]
Fixed
