### ISSUE TITLE
Search bar does not work

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#255]
## Describe the bug

Audio button does not work on the search bar when pressed

the search bar does not work when you try to search for a food item

## To Reproduce
1. Go to 'restaurant'
2. Click on '.search bar audio icon or fill in in a food item'
3. Press 'enter'

## Expected behavior

You should be able to search for o food item in the inventory and use the audio button to also search

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/186844623-4c5faf8e-f472-4481-8a54-a6f035e7f497.png)

![image](https://user-images.githubusercontent.com/102152014/186844652-bf19c430-7bce-4ff4-b060-afdd3f0cd7cf.png)

![image](https://user-images.githubusercontent.com/102152014/186844696-58527690-e3c6-48ca-bd01-28a7164bca59.png)

## Desktop (Alba Tablet):
 - OS: [Android]
 - Browser [Chrome]

**Comment by abumunye** [comment]
Removed temprarily
