### ISSUE TITLE
Checkout does not load

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#256]
## Describe the bug

When you press the checkout section it continuously loads

## To Reproduce
1. Go to 'checkout section'
2. See error

## Expected behavior

The checkout section loads and allows you to pay

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/186844920-0020c301-dbfe-4fc7-9c51-4cd34c8095d8.png)

![image](https://user-images.githubusercontent.com/102152014/186844930-3c31f088-a1cd-4e35-90ae-24b42d82719d.png)

## Desktop (Alba Tablet):
 - OS: [Android]
 - Browser [Chrome]

**Comment by abumunye** [comment]
Fixed
