### ISSUE TITLE
Logged in to wrong account with wrong details

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#257]
## Describe the bug
The wrong account seems to be logged in to when I log in to my account or there is a defult account that everyone logs in to.
1. Wrong name than the one I logged in with
2. incorrect number (American although I  signed in with British)

## To Reproduce
1. Go to 'log in'
3. Click on 'pull left side bar'

## Expected behavior
When I log in to my account I see my details

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/187383953-5295d97a-3876-4731-bba0-3e33d8a9dcd2.png)

## Desktop (alba Tablet from Salim Manager):
 - OS: [Android]
 - Browser [Chrome]

**Comment by abumunye** [comment]
Fixed
