### ISSUE TITLE
Hamburger menu almost invisible

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#258]
## Describe the bug

The hamburger menu is almost invisible as it it similar to the color of the background, it was not visible so i did not know it was there till I was told. It was not too visible on the tablet but was more visible on a bigger screen (my laptop) but still barely visible

## To Reproduce
1. Go to 'home page'
2. look for 'hamburger menu on the top left hand side'

## Expected behavior

The lines of the hamburger menu are clearly visible so that the customer can know that there are more tabs on the app

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/187635926-d194ac00-1187-49b1-adac-6c4db411b7cd.png)

![image](https://user-images.githubusercontent.com/102152014/187635991-f599cfcb-211e-41fe-9d03-ded1b2757804.png)

## Desktop (please complete the following information):
 - OS: [my laptop]
 - Browser [chrome]

**Comment by abumunye** [comment]
Fixed
