### ISSUE TITLE
No favorite foods button

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#259]
## Describe the bug
There is a favorite food section on the hamburger menu however when you go on to a restaurant there is no option to favorite foods

## To Reproduce
1. Go to 'home page'
2. Click on 'restaurant'
3. try to find a place to 'favorite foods'

## Expected behavior
There is a button or section that allows you to favorite food

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/187637456-5db54c27-acb1-42b2-99cb-40289df53549.png)

![image](https://user-images.githubusercontent.com/102152014/187637480-6328ad33-becf-4563-9441-8e30668a37e7.png)

## Desktop (My laptop):
 - OS: [Windows]
 - Browser [Chrome]

**Comment by abumunye** [comment]
Removed
