### ISSUE TITLE
Unresponsive hamburger menue

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#260]
## Describe the bug
the buttons on the hamburger menue are not responsive

## To Reproduce
1. Go to 'home page'
2. Click on 'hamburger menu'
3. . See error

## Expected behavior

The buttons work on the hamburger menu

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/187638889-5ff29318-5898-4111-8c8b-6bbdb335811b.png)

## Desktop (Dell laptop):
 - OS: [Windows]
 - Browser [Chrome]

**Comment by abumunye** [comment]
Fixed
