### ISSUE TITLE
Default orange profile picture 

### ISSUE THREAD

**Issue by TamarindSpice** [abumunye/orderpin-bugs#261]
## Describe the bug
you cannot change the image for the user profile picture as it is defult

## To Reproduce
1. Go to hamburger menu'
2. Click on 'image'

## Expected behavior
You can change the profile picture

## Screenshots

![image](https://user-images.githubusercontent.com/102152014/187641556-eef44585-c1a0-4aa7-a6f1-6d26b1ec37eb.png)

## Desktop (Dell Laptop):
 - OS: [Windows]
 - Browser [chrome]

**Comment by abumunye** [comment]
Removed profile picture
