### ISSUE TITLE
Typing the password in the guest sign in page doesn’t censor it

### ISSUE THREAD

**Issue by abumunye** [abumunye/orderpin-bugs#3]
## Describe the bug
Typing the password in the guest sign in page doesn’t censor it

## To Reproduce
1. Open app
2. Click guest user
3. Type password

## Expected behavior
Password should be censored like the main sign in page

## Screenshots
<img src="https://user-images.githubusercontent.com/40043711/159250197-ec568e98-642d-4b2a-b2fc-4bc4c2131ed2.png" width="300">

## Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 9

**Comment by xmxdeus** [comment]
Bug Fixed
