### ISSUE TITLE
Sidebar misspelled income expenditure 

### ISSUE THREAD

**Issue by abumunye** [abumunye/orderpin-bugs#4]
## Describe the bug
Sidebar misspelled income expenditure 

## To Reproduce
1. Sign in to boss hero
2. Swipe right to open sidebar
3. Look at second element in the 

## Expected behavior
Expected spelling to be Income Expenditure not Income Expanditure

## Screenshots
<img src="https://user-images.githubusercontent.com/40043711/159250837-6b7d1ac5-23a6-4333-b170-43ffef2c345a.png" width="300">

## Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 9

**Comment by xmxdeus** [comment]
Bug Fixed
