### ISSUE TITLE
Dashboard misspelled in the appbar

### ISSUE THREAD

**Issue by abumunye** [abumunye/orderpin-bugs#5]
## Describe the bug
Dashboard misspelled in the appbar of the home page

## To Reproduce
1. Sign in to bosshero
2. Look at appbar

## Expected behavior
Should be spelled "Dashboard" not "DashBord"

## Screenshots
<img src="https://user-images.githubusercontent.com/40043711/159252143-9ecd803b-1152-4e7a-acbe-da0fd209bc71.png" width="300">

## Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 9

**Comment by xmxdeus** [comment]
Bug Fixed
