### ISSUE TITLE
Dashboard Graph Out Of Screen

### ISSUE THREAD

**Issue by abumunye** [abumunye/orderpin-bugs#6]
## Describe the bug
When your expenses go over your budget the graph goes above it’s container

## To Reproduce
1. Open App.
2. Sign in
3. Add a budget month to some amount using bottom right button
4. Add an expense larger than the amount
5. Possibly log in and out if graph doesn’t show

## Expected behavior
Maybe the graph should cut off the part that goes above the screen

## Screenshots
<img src="https://user-images.githubusercontent.com/40043711/159252901-2a2ead5c-0dc3-4573-a04a-228261c9fdb6.png" width="300">

## Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 9

**Comment by xmxdeus** [comment]
Bug Fixed
