### ISSUE TITLE
Expenses increasing bug

### ISSUE THREAD

**Issue by abumunye** [abumunye/orderpin-bugs#7]
## Describe the bug
When you go to the expenses tracker then go back to the dashboard your total expenses for the month increases by the amount of expenses you have in your expenses tracker

## To Reproduce
1. Open App.
2. Sign in
3. Add a budget month to some amount using bottom right button
4. Add some expenses using the bottom right button
5. Go to the expenses page using the sidebar
6. Go back to the dashboard
7. Expenses should have increased

## Expected behavior
Expenses should only increase when you add a new expense

## Screenshots
<img src="https://user-images.githubusercontent.com/40043711/159253198-f6b24aaf-80d0-47b7-a180-c52f3b86e167.png" width="300">
<img src="https://user-images.githubusercontent.com/40043711/159253239-1e036a7e-7d0f-4675-83c6-84bd94ee0135.png" width="300">
<img src="https://user-images.githubusercontent.com/40043711/159253278-bd0a70e4-2280-42d0-be24-e0725efe4bf4.png" width="300">

Expenses before: 35602.
Expenses in expenses tracker: 5086
40688 - 5086 = 35602

When you log out and log back in it fixes it.

## Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 9

**Comment by xmxdeus** [comment]
Bug Fixed

**Comment by abumunye** [comment]
not fixed I can still replicate this maybe you need to have expenses and income for the bug to occur

**Comment by xmxdeus** [comment]
Bug fixed, the value kept on being added as you refresh - the value hasn't been cleared and every time the api is called it would stack old expenses to total expenses previously shown,
