### ISSUE TITLE
Total expenses misspelling

### ISSUE THREAD

**Issue by abumunye** [abumunye/orderpin-bugs#8]
## Describe the bug
Total expenses misspelled in the dashboard

## To Reproduce
1. Open App.
2. Sign in
3. Observe the "Total Expansese for the month"

## Expected behavior
Should be spelled “Total Monthly Expenses”

## Screenshots
<img src="https://user-images.githubusercontent.com/40043711/159253833-ae3efc09-9cae-454d-99d6-2cc43e88faa9.png" width="300">

## Smartphone (please complete the following information):
 - Device: Pixel 2
 - OS: Android 9

**Comment by xmxdeus** [comment]
Bug Fixed
